[package]
name = "studious-octo-enigma"
version = "0.1.0"
authors = ["nannany <ymym1990ymym@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
rand = "0.8.3"
